[package]
name = "local-edf-reader"
version = "0.1.0"
authors = ["Maxime Leprince <maxime.leprince@bioserenity.com>"]
edition = "2018"

[dependencies]
edf-reader="0.4.0"
futures="0.1"
positioned-io = "0.2.2"


[dev-dependencies]
assert_approx_eq = "1.1.0"
